spring:
  application:
    name: Eureka Server
server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
